<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="/node_modules/jquery/dist/jquery.min.js"></script>
  <script src="/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>

  <link href="/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="/node_modules/bootstrap/dist/css/bootstrap-theme.min.css" rel="stylesheet">
  <link href="/node_modules/font-awesome/css/font-awesome.min.css" rel="stylesheet">
  <link href="/node_modules/bootstrap-social/bootstrap-social.css" rel="stylesheet">

  <link rel="stylesheet" href="/assets/css/order-form.css">
  <link rel="stylesheet" href="/assets/css/cart.css">

  <title><?= $this->data['title'] ?></title>
</head>
