<section class="row">
  <div class="table-responsive">

    <?php if($this->data['clients'] != null): ?>

    <table class="table table-striped table-hover">
      <caption><?=$this->data['title']?></caption>
      <thead class="thead-default">
        <tr>
          <th>id</th>
          <th>lastname</th>
          <th>firstname</th>
          <th>address</th>
          <th>siret</th>
          <th>phone</th>
          <th>mail</th>
        </tr>
      </thead>

      <tbody>
        <?php  for ($i = 0; $i < count($this->data['clients']); ++$i) {
          ?>
          <?php $client = $this->data['clients'][$i]; ?>
          <tr>
            <td>
              <a href="admin/client?id=<?=
              $client['id']
              ?>"><?= $client['id'] ?></a>
            </td>
            <td><?= $client['lastname'] ?></td>
            <td><?= $client['firstname'] ?></td>
            <td><?= $client['address'] ?></td>
            <td><?= $client['siret'] ?></td>
            <td><?= $client['phone'] ?></td>
            <td><?= $client['mail'] ?></td>
          </tr>

          <?php

        } ?>
      </tbody>
    </table>
    <?php endif ?>

  </div>
</section>
