<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/admin">
                <img src="/assets/images/logo.jpg" height="30" width="41">
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li <?php if(!strcasecmp($this->data['activeLink'],'client')) {echo "class=\"active\"";}?>>
                    <a href="/admin/clients">
                      <i class="fa fa-users" aria-hidden="true"></i>
                        Clients</a>
                </li>
                <li <?php if(!strcasecmp($this->data['activeLink'],'bill')) {echo "class=\"active\"";}?>>
                    <a href="/admin/bills">
                      <i class="fa fa-file" aria-hidden="true"></i>
                        Bills</a>
                </li>
                <li <?php if(!strcasecmp($this->data['activeLink'],'article')) {echo "class=\"active\"";}?>>
                    <a href="/admin/articles">
                      <i class="fa fa-cubes" aria-hidden="true"></i>
                       Articles</a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <li>
                <a type="button" id="logoutbutton" href="/admin/logout">
                  <!-- data-toggle="modal" data-target="#loginModal"-->
                  <span class="glyphicon glyphicon-log-out"></span> Logout</a>
                </li>
            </ul>

        </div>
    </div>
</nav>

<div id="logoutModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">logout</h4>
        </div>
        <div class="modal-body">
          <form class="form-inline" action="">
            <div class="form-group">
              <button type="submit" class="btn btn-info">Sign in</button>
              <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
            </div>
          </form>
        </div>
      </div>
    </div>
</div>
