<section class="row">
<div class="table-responsive">

  <?php if($this->data['bills'] != null): ?>

  <table class="table table-striped table-hover">
    <caption><?=$this->data['title']?></caption>
    <thead class="thead-default">
      <tr>
        <th>id</th>
        <th>creationdate</th>
        <th>payment_date</th>
        <th>client_id</th>
      </tr>
    </thead>

    <tbody>
      <?php  for ($i = 0; $i < count($this->data['bills']); ++$i) {
     ?>
        <?php $bill = $this->data['bills'][$i]; ?>
        <tr>
          <td>
            <a href="bill?id=<?=
            $bill['id']
            ?>"><?= $bill['id'] ?></a>
          </td>
          <td><?= $bill['creationdate'] ?></td>
          <td><?= $bill['payment_date'] ?></td>
          <td><?= $bill['client_id'] ?></td>
        </tr>

        <?php

 } ?>
    </tbody>
  </table>
  <?php endif ?>

</div>
</section>
