
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Exo</title>
	<script   src="https://code.jquery.com/jquery-3.1.0.js"   integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk="   crossorigin="anonymous"></script>
</head>
<body>

	<table>
		<tr>
			<td class="<?= 3 ?>">5</td>
			<td onclick="buy(<?= 3 ?>)">+++</td>
		</tr>
		<tr>
			<td class="<?= 4 ?>">10</td>
			<td onclick="buy(<?= 4 ?>)">+++</td>
		</tr>
	</table>

	<script type="text/javascript">

	function buy(id){
		//afficher le nombre correspondant à la ligne dans un alert
		console.log(id);
		var number = $('.' + id).text();
		console.log("number = ", number);
		// window.alert(number);

	}
	</script>

</body>
</html>
