<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Exo</title>
        <script src="https://code.jquery.com/jquery-3.1.0.js" integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk=" crossorigin="anonymous"></script>
    </head>
    <body>

        <table>
            <tr>
                <td class="<?php echo "fruitId3" ?>">poires</td>
                <td class="<?php echo "id3"; ?>">5</td>
                <td onclick="handle(<?= 3 ?>)">++++++</td>
            </tr>
            <tr>
                <td class="<?php echo "fruitId4" ?>">pommes</td>
                <td class="<?php echo "id4"; ?>">10</td>
                <td onclick="handle(<?= 4 ?>)">++++++</td>
            </tr>
        </table>
    </html>

    <script type="text/javascript">

        function handle(id) {
            //afficher le nombre correspondant à la ligne dans un alert, par exemple : "5 pommes"

            console.log(id);
            var number = $('.id' + id).text();
            var fruit = $('.fruitId' + id).text();
            console.log("number = ", number);
            console.log("fruit = ", fruit);
            window.alert(number + " " + fruit);
        }
    </script>
