# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
              users:
                julien:
                  password: 2118c37356b669d52c22510c0287642551fcdc1b9b27517999e040ad56d1ad678cb71496eb4da19832143ae14ef1ceabf1824349bd608176a91f22f7088a5427
                  roles: 'ROLE_USER'

        in_db:
          entity:
            class: AppBundle:User
            property: userName

    encoders:
      Symfony\Component\Security\Core\User\User: sha512
      AppBundle\Entity\User: sha512

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: in_db
            pattern: ^/
            anonymous: ~
            # activate different ways to authenticate

            form_login:
              login_path: /login
              check_path: /login
              default_target_path: /account
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            logout:
               path: /logout
               target: /


    access_control:
      # require ROLE_ADMIN for /admin*
      # - { path: ^/admin, roles: ROLE_ADMIN }

      # require ROLE_USER for /account*
      - { path: ^/account, roles: ROLE_USER }

      - { path: ^/meeting/new, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
      - { path: ^/meeting, roles: ROLE_USER }
