<div id="logoutModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">logout</h4>
        </div>
        <div class="modal-body">
          <form class="form-inline" action="">
            <div class="form-group">
              <button type="submit" class="btn btn-info">Sign in</button>
              <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
            </div>
          </form>
        </div>
      </div>
    </div>
</div>
