<section id="registerModal" class="modal fade" role="dialog">
  <article class="modal-dialog">
    <div class="modal-content">

      <header class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Register</h4>
      </header>

      <main class="modal-body">
        <form class="form" action="/register" method="post">

            <div class="form-group">
              <label>Firstname</label>
              <input type="text" name="firstname" class="form-control">
            </div>
            <div class="form-group">
              <label>Lastname</label>
              <input type="text" name="lastname" class="form-control">
            </div>

          <div class="form-group">
            <label>Siret Number</label>
            <input type="text" name="siret" size="14" class="form-control" required>
          </div>

          <div class="form-group">
            <label>Email Address</label>
            <input type="email" name="email" placeholder="Enter Email Address Here.." class="form-control" required>
          </div>
          <div class="form-group">
            <label>Password</label>
            <input type="password" name="password" placeholder="Enter password Here.." class="form-control" required>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-info">Sign Up</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
          </div>

        </form>
      </main>

    </div>
  </article>
</section>
