<div id="loginModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Login</h4>
      </div>
      <div class="modal-body">
        <form class="form-inline" method="post" action="login">
          <div class="form-group">
            <label class="sr-only" for="email"> Email address</label>
            <input type="email" class="form-control input-sm" name="email" placeholder="Email" required>
          </div>
          <div class="form-group">
            <label class="sr-only" for="password">Password</label>
            <input type="password" class="form-control input-sm" name="password" placeholder="Password" required>
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember me
            </label>
          </div>
          <div class="form-group">
            <button type="submit" class="btn btn-info">Sign in</button>
            <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancel</button>
          </div>
        </form>
      </div>
    </div>

  </div>
</div>
