vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        devis:
            uri_prefix: /devis/
            upload_destination: '%kernel.root_dir%/../public/devis'
            namer: vich_uploader.namer_uniqid

#            inject_on_load:     false
#            delete_on_update:   true
#            delete_on_remove:   true